---
- name: Creating a webserver
  hosts: all
  vars_files:
    - variables.yaml
  become: true
  tasks:
    - name: "Installing apache ({{ pkg_name }})"
      dnf:
        name: "{{ pkg_name }}"
        state: latest

    - name: Starting the apache service
      systemd:
        name: "{{ pkg_name }}"
        state: started
        enabled: true

    - name: Copy website into the nodes
      copy:
        src: index.html
        dest: /var/www/html

    - name: Print the data
      debug:
        msg: "{{ data_print }}"
